"""
Phase 2 - Step 1: Random Forest + XGBoost training
Connect Four AI - move prediction from board state

Trains models to predict `chosen_column` (the move an AI/minimax-driven
player would make) from the board state (`board_flat`) plus light
engineered features. Uses the MERGED dataset: self-play CSV + real
gameplay CSV exported from connect_4.py.

Run this from the Connect-Four-Project folder (so relative paths to
datasets/ work), or edit SELF_PLAY_CSV / REAL_CSV below to absolute paths.
"""

import os
import json
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, top_k_accuracy_score
import xgboost as xgb
import joblib

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
SELF_PLAY_CSV = "datasets/continuous_gameplay_log.csv"          # generated by generate_selfplay_data.py
REAL_CSV = "datasets/continuous_gameplay_log_real.csv"           # rename your real CSV to this, OR edit path below
OUTPUT_DIR = "models"
RANDOM_STATE = 42

ROW_COUNT = 6
COLUMN_COUNT = 7

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ---------------------------------------------------------------------------
# 1. Load + merge
# ---------------------------------------------------------------------------
def load_and_merge(self_play_path, real_path):
    self_play = pd.read_csv(self_play_path)
    self_play["data_source"] = "self_play"

    if real_path and os.path.exists(real_path):
        real = pd.read_csv(real_path)
        real["data_source"] = "real_gameplay"
        merged = pd.concat([self_play, real], ignore_index=True)
    else:
        print(f"[WARN] Real gameplay CSV not found at {real_path}, using self-play only.")
        merged = self_play

    return merged


# ---------------------------------------------------------------------------
# 2. Filter to AI-decision rows (rows with a real minimax_score)
#    These are the rows where a minimax-driven agent chose chosen_column.
#    PVP human-vs-human rows (no minimax_score) are excluded since there's
#    no "correct" AI move to learn from.
# ---------------------------------------------------------------------------
def filter_ai_decisions(df):
    df = df.copy()
    df["minimax_score"] = pd.to_numeric(df["minimax_score"], errors="coerce")
    ai_rows = df[df["minimax_score"].notna()].reset_index(drop=True)
    return ai_rows


# ---------------------------------------------------------------------------
# 3. Feature engineering from board_flat
#    - 42 raw cell values (0=empty, 1=player, 2=AI) as features
#    - column heights (how many pieces in each column already)
#    - whose turn it is encoded (player vs AI-side) via piece counts
# ---------------------------------------------------------------------------
def parse_board(board_flat_str):
    return np.array([int(x) for x in board_flat_str.split(",")], dtype=np.int8)


def engineer_features(df):
    boards = np.vstack(df["board_flat"].apply(parse_board).values)  # (N, 42)

    cell_cols = [f"cell_{i}" for i in range(42)]
    feat_df = pd.DataFrame(boards, columns=cell_cols)

    # Column heights: count of non-zero cells per column (7 cols x 6 rows, row-major flatten r*7+c)
    board_grid = boards.reshape(-1, ROW_COUNT, COLUMN_COUNT)
    col_heights = (board_grid != 0).sum(axis=1)  # (N, 7)
    for c in range(COLUMN_COUNT):
        feat_df[f"col_height_{c}"] = col_heights[:, c]

    # Piece counts (board balance / turn signal)
    feat_df["player_piece_count"] = (boards == 1).sum(axis=1)
    feat_df["ai_piece_count"] = (boards == 2).sum(axis=1)
    feat_df["total_pieces"] = (boards != 0).sum(axis=1)

    # Categorical context features
    feat_df["game_mode"] = df["game_mode"].fillna("UNKNOWN")
    feat_df["difficulty"] = df["difficulty"].fillna("UNKNOWN")
    feat_df["data_source"] = df["data_source"]

    feat_df = pd.get_dummies(feat_df, columns=["game_mode", "difficulty", "data_source"])

    target = df["chosen_column"].astype(int)

    return feat_df, target


# ---------------------------------------------------------------------------
# 4. Train Random Forest
# ---------------------------------------------------------------------------
def train_random_forest(X_train, y_train, X_test, y_test):
    rf = RandomForestClassifier(
        n_estimators=300,
        max_depth=20,
        min_samples_split=4,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    rf.fit(X_train, y_train)

    pred = rf.predict(X_test)
    proba = rf.predict_proba(X_test)

    acc = accuracy_score(y_test, pred)
    top3 = top_k_accuracy_score(y_test, proba, k=3, labels=rf.classes_)

    print("\n=== Random Forest ===")
    print(f"Top-1 Accuracy: {acc:.4f}")
    print(f"Top-3 Accuracy: {top3:.4f}")
    print(classification_report(y_test, pred, zero_division=0))

    return rf, {"top1_accuracy": acc, "top3_accuracy": top3}


# ---------------------------------------------------------------------------
# 5. Train XGBoost
# ---------------------------------------------------------------------------
def train_xgboost(X_train, y_train, X_test, y_test, num_classes):
    xgb_model = xgb.XGBClassifier(
        n_estimators=300,
        max_depth=8,
        learning_rate=0.1,
        objective="multi:softprob",
        num_class=num_classes,
        eval_metric="mlogloss",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    xgb_model.fit(X_train, y_train)

    pred = xgb_model.predict(X_test)
    proba = xgb_model.predict_proba(X_test)

    acc = accuracy_score(y_test, pred)
    top3 = top_k_accuracy_score(y_test, proba, k=3, labels=np.arange(num_classes))

    print("\n=== XGBoost ===")
    print(f"Top-1 Accuracy: {acc:.4f}")
    print(f"Top-3 Accuracy: {top3:.4f}")
    print(classification_report(y_test, pred, zero_division=0))

    return xgb_model, {"top1_accuracy": acc, "top3_accuracy": top3}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("Loading and merging datasets...")
    merged = load_and_merge(SELF_PLAY_CSV, REAL_CSV)
    print(f"Merged dataset: {merged.shape[0]} rows")

    print("Filtering to AI-decision rows (has minimax_score)...")
    ai_rows = filter_ai_decisions(merged)
    print(f"AI-decision rows: {ai_rows.shape[0]}")
    print(ai_rows["player"].value_counts().to_string())

    print("\nEngineering features...")
    X, y = engineer_features(ai_rows)
    print(f"Feature matrix: {X.shape}, target classes: {sorted(y.unique())}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
    )
    print(f"Train: {X_train.shape[0]} rows, Test: {X_test.shape[0]} rows")

    num_classes = int(y.max()) + 1  # columns 0-6 -> 7 classes

    rf_model, rf_metrics = train_random_forest(X_train, y_train, X_test, y_test)
    xgb_model, xgb_metrics = train_xgboost(X_train, y_train, X_test, y_test, num_classes)

    # Feature importance (top 15) for the paper's results section
    rf_importances = pd.Series(rf_model.feature_importances_, index=X.columns).sort_values(ascending=False)
    print("\nTop 15 Random Forest feature importances:")
    print(rf_importances.head(15).to_string())

    # Save models
    joblib.dump(rf_model, os.path.join(OUTPUT_DIR, "random_forest_model.joblib"))
    xgb_model.save_model(os.path.join(OUTPUT_DIR, "xgboost_model.json"))
    joblib.dump(list(X.columns), os.path.join(OUTPUT_DIR, "feature_columns.joblib"))

    # Save metrics summary (for paper Table II)
    summary = {
        "dataset_rows_total": int(merged.shape[0]),
        "ai_decision_rows": int(ai_rows.shape[0]),
        "train_rows": int(X_train.shape[0]),
        "test_rows": int(X_test.shape[0]),
        "num_features": int(X.shape[1]),
        "random_forest": rf_metrics,
        "xgboost": xgb_metrics,
        "data_sources": ai_rows["data_source"].value_counts().to_dict(),
    }
    with open(os.path.join(OUTPUT_DIR, "training_summary.json"), "w") as f:
        json.dump(summary, f, indent=2)

    print(f"\nSaved models + summary to {os.path.abspath(OUTPUT_DIR)}/")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
